name: 'Terraform Herbalife Prod'

on:
  push:
    branches: [ "herbalife-dev" ]
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Herbalife Prod'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: lakehouse
      run: terraform init -reconfigure

    - name: Terraform Plan (Herbalife Prod)
      working-directory: lakehouse
      run: terraform plan

    - name: Terraform Apply (Herbalife Prod)
      working-directory: lakehouse
      run: terraform apply -auto-approve
